const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db;const seed={customers:[{id:'sara',name:'سارة',phone:'0500000001',consent:false},{id:'reem',name:'ريم',phone:'0500000002',consent:true},{id:'lina',name:'لينا',phone:'0500000003',consent:false}],messages:{sara:['مرحبًا، أحتاج معلومات عن الخدمات.'],reem:['شكرًا على المتابعة.'],lina:['ما هي ساعات العمل؟']},campaigns:[],business:{name:'نشاطك',services:'',hours:'',faq:''}};
try{db=JSON.parse(localStorage.getItem('tugx-v3'))||structuredClone(seed)}catch{db=structuredClone(seed)}
function notify(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4500)}
function save(next){try{localStorage.setItem('tugx-v3',JSON.stringify(next));db=next;return true}catch{notify('تعذر حفظ التغييرات. حاول مرة أخرى؛ ما كتبته ما زال موجودًا.');return false}}
const names={dashboard:'نظرة عامة',inbox:'المحادثات',campaigns:'الحملات',customers:'العملاء',templates:'القوالب',automation:'الأتمتة',ai:'مساعد توجيكس AI',settings:'الإعدادات',help:'المساعدة'},wa=['inbox','campaigns','customers','templates','automation'];
const main=document.querySelector('main');
main.innerHTML='<header><button class="mobile-menu" aria-label="فتح القائمة" aria-expanded="false">☰</button><div class="crumb"></div><a href="#/help">المساعدة</a></header><div class="demo-banner">نسخة تجريبية — البيانات المعروضة توضيحية. الحفظ على هذا المتصفح فقط، ولا يتم إرسال رسائل فعلية.</div><div id="connection" role="status"></div><section id="screen" class="view active"></section>';
document.querySelector('.sidebar nav').innerHTML=['dashboard','inbox','ai'].map(k=>'<a class="nav" href="#/'+k+'" data-nav="'+k+'">'+(k==='inbox'?'واتساب بزنس':names[k])+'</a>').join('');
document.querySelector('.sidebar-bottom').innerHTML='<a class="nav" href="#/settings">الإعدادات</a><a class="nav" href="#/help">المساعدة</a><div class="user">مساحة العمل التجريبية</div>';
const screen=document.getElementById('screen');
function route(){const p=location.hash.slice(1).split('/').filter(Boolean);return{page:names[p[0]]?p[0]:'dashboard',id:p[1]||''}}
function tabs(page){return '<nav class="wa-tabs" aria-label="أقسام واتساب">'+wa.map(k=>'<a href="#/'+k+'" class="'+(k===page?'selected':'')+'" '+(k===page?'aria-current="page"':'')+'>'+names[k]+(['templates','automation'].includes(k)?'<small>قريبًا</small>':'')+'</a>').join('')+'</nav>'}
function heading(t,d,a=''){return '<div class="page-title"><div><h1>'+t+'</h1><p>'+d+'</p></div>'+a+'</div>'}
function btn(t,a){return '<button class="primary" data-action="'+a+'">'+t+'</button>'}
function render(){
const {page,id}=route();document.title=names[page]+' | توجيكس';document.querySelector('.crumb').innerHTML=esc(db.business.name)+' / '+(wa.includes(page)?'<a href="#/inbox">واتساب بزنس</a> ← ':'')+names[page];
document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(wa.includes(page)?'inbox':page)));document.querySelector('.sidebar').classList.remove('mobile-open');document.querySelector('.mobile-menu').setAttribute('aria-expanded','false');
if(page==='dashboard')screen.innerHTML='<section class="welcome"><div><span class="live-pill"><i></i> مساحة عملك جاهزة</span><h1>حوّل كل محادثة<br><em>إلى فرصة نمو.</em></h1><p>مركز واحد يجمع محادثاتك وعملاءك وحملاتك، ويجهّز أعمالك للمرحلة التالية.</p><div class="welcome-actions"><a class="primary" href="#/inbox">افتح مركز واتساب <span>←</span></a><a class="ghost-action" href="#/campaigns">جهّز حملة</a></div></div><div class="orbit-visual" aria-hidden="true"><div class="orbit-core"><span>tug<b>x</b></span><small>control center</small></div><i class="orbit-ring ring-one"></i><i class="orbit-ring ring-two"></i><span class="orbit-dot dot-one">↗</span><span class="orbit-dot dot-two">✦</span><span class="orbit-dot dot-three">◌</span></div></section><div class="section-label"><div><span>لمحة مباشرة</span><h2>نبض مساحة العمل</h2></div><small>آخر تحديث الآن</small></div><div class="stats premium-stats"><article><span class="metric-icon violet">◎</span><p>العملاء</p><h2>'+db.customers.length+'</h2><small>سجلات تجريبية</small><a href="#/customers" aria-label="عرض العملاء">←</a></article><article><span class="metric-icon coral">↗</span><p>مسودات الحملات</p><h2>'+db.campaigns.length+'</h2><small>جاهزة للمراجعة</small><a href="#/campaigns" aria-label="عرض الحملات">←</a></article><article><span class="metric-icon cyan">◌</span><p>اتصال واتساب</p><h2 class="metric-text">بانتظار الربط</h2><small>Meta Cloud API</small><a href="#/settings" aria-label="تفاصيل الاتصال">←</a></article><article><span class="metric-icon lime">✦</span><p>مساعد توجيكس</p><h2 class="metric-text">قيد الإعداد</h2><small>قاعدة المعرفة</small><a href="#/ai" aria-label="إعداد المساعد">←</a></article></div><div class="dashboard-grid"><section class="card attention-card"><div class="card-kicker">خطوتك التالية</div><h2>جهّز الأساس، ثم انطلق.</h2><p>أكمل هذه الخطوات لتصبح مساحة العمل جاهزة عند ربط الخدمات الفعلية.</p><div class="journey"><a href="#/customers"><b>01</b><span><strong>أضف عملاءك</strong><small>نظّم البيانات والموافقات</small></span><i>←</i></a><a href="#/ai"><b>02</b><span><strong>عرّف نشاطك</strong><small>الخدمات والأسعار والأوقات</small></span><i>←</i></a><a href="#/campaigns"><b>03</b><span><strong>أنشئ أول مسودة</strong><small>خصص الرسالة وراجع الجمهور</small></span><i>←</i></a></div></section><section class="card signal-card"><div class="signal-head"><div><span>حالة المنصة</span><h3>جاهزية التكامل</h3></div><b>35%</b></div><div class="progress"><i></i></div><div class="signal-list"><p><i class="done"></i><span>واجهة تجربة العملاء</span><b>مكتمل</b></p><p><i class="done"></i><span>إدارة المسودات</span><b>مكتمل</b></p><p><i></i><span>ربط WhatsApp Cloud API</span><b>التالي</b></p><p><i></i><span>تشغيل المساعد الذكي</span><b>لاحقًا</b></p></div><a href="#/settings" class="text-link">تفاصيل التكامل ←</a></section></div>';
if(page==='inbox'){
const c=db.customers.find(x=>x.id===id);
screen.innerHTML=heading('واتساب بزنس','نظّم محادثات العملاء، وتابع الطلبات، ووزّع العمل على فريقك.',btn('بدء محادثة','start'))+tabs(page)+'<div class="inbox '+(c?'chat-open':'')+'"><aside class="conversations"><input id="search" aria-label="بحث المحادثات" placeholder="ابحث باسم العميل أو رقم الجوال"><div id="list"></div></aside><section class="chat">'+(c?'<div class="chat-head"><a class="outline" href="#/inbox">المحادثات</a><strong>'+esc(c.name)+'</strong><span>محادثة توضيحية</span></div><div class="messages">'+(db.messages[id]||[]).map(m=>'<div class="message '+(typeof m==='object'?'outbound':'inbound')+'">'+esc(typeof m==='object'?m.text:m)+'<small>'+(typeof m==='object'?'محفوظ محليًا — لم يُرسل':'رسالة توضيحية')+'</small></div>').join('')+'</div><form id="reply" class="composer"><input name="text" aria-label="الرسالة" required maxlength="4000" placeholder="اكتب ردًا تجريبيًا…"><button class="send">حفظ الرد التجريبي</button></form>':'<div class="empty"><h2>اختر محادثة</h2><p>تظهر هنا رسائل العميل المحدد.</p></div>')+'</section></div>';
list('');document.getElementById('search').oninput=e=>list(e.target.value);document.getElementById('reply')?.addEventListener('submit',e=>{e.preventDefault();const text=e.target.text.value.trim();if(!text)return;const next=structuredClone(db);(next.messages[id]??=[]).push({text});if(save(next)){render();notify('حُفظ الرد في التجربة فقط. لم يُرسل إلى واتساب.')}});
}
if(page==='customers'){const subscribed=db.customers.filter(x=>x.consent).length;screen.innerHTML=heading('العملاء','احتفظ ببيانات عملائك وسجل تواصلهم وتصنيفاتهم في مكان واحد.',btn('إضافة عميل','customer'))+tabs(page)+'<div class="mini-metrics"><article><span>إجمالي العملاء</span><b>'+db.customers.length+'</b><small>سجل محفوظ</small></article><article><span>موافقون على الحملات</span><b>'+subscribed+'</b><small>Opt-in موثّق</small></article><article><span>بحاجة للمراجعة</span><b>'+(db.customers.length-subscribed)+'</b><small>دون موافقة حملات</small></article></div><section class="card directory-card"><div class="directory-head"><div><span class="card-kicker">دليل العملاء</span><h2>قاعدة عملائك</h2></div><input class="search-field" id="search" aria-label="بحث العملاء" placeholder="ابحث باسم العميل أو رقم الجوال"></div><div id="list"></div></section>';list('');document.getElementById('search').oninput=e=>list(e.target.value)}
if(page==='campaigns')screen.innerHTML=heading('الحملات','أنشئ حملات لعملائك المشتركين، وحدد جمهورك، وتابع النتائج.',btn('إنشاء مسودة حملة','campaign'))+tabs(page)+'<section class="campaign-hero"><div><span>استوديو الحملات</span><h2>رسالة مناسبة،<br>للعميل المناسب.</h2><p>ابنِ حملات واتساب منظمة واحفظها للمراجعة قبل تفعيل الإرسال الفعلي.</p><div class="campaign-pills"><b>تقسيم الجمهور</b><b>تخصيص الاسم</b><b>معاينة قبل الحفظ</b></div></div><div class="campaign-orb"><i></i><strong>'+db.campaigns.length+'</strong><small>مسودات</small></div></section><div class="section-label"><div><span>مساحة العمل</span><h2>مسودات الحملات</h2></div><small>الإرسال والجدولة الفعلية قيد التطوير</small></div><section class="card campaign-list">'+(db.campaigns.map(c=>'<div class="campaign-item"><span class="campaign-symbol">↗</span><div><strong>'+esc(c.name)+'</strong><small>مسودة محفوظة محليًا</small></div><span class="status draft">مسودة</span><button class="outline" data-campaign="'+c.id+'">عرض وتعديل</button></div>').join('')||'<div class="empty premium-empty"><span>↗</span><h2>حملتك الأولى تبدأ هنا</h2><p>اختر جمهورك وجهّز رسالتك، ثم راجعها قبل حفظ المسودة.</p>'+btn('أنشئ أول مسودة','campaign')+'</div>')+'</section>';
if(['templates','automation'].includes(page))screen.innerHTML=heading(names[page],'واتساب بزنس')+tabs(page)+'<section class="card empty"><span>قريبًا</span><h2>هذه الميزة قيد التطوير، وستتوفر لاحقًا.</h2><a href="#/inbox">العودة إلى محادثات واتساب</a></section>';
if(page==='ai')screen.innerHTML=heading(names.ai,'زوّد مساعدك بمعلومات نشاطك، واختبر إجاباته قبل تفعيل الرد التلقائي.')+'<section class="ai-stage"><div class="ai-copy"><span class="status draft">غير مفعّل — الربط قريبًا</span><div class="ai-glyph">✦</div><h2>ذكاء يعرف نشاطك،<br><em>ولا يخمّن.</em></h2><p>نظّم الخدمات والأسعار وساعات العمل والأسئلة الشائعة، لتصبح قاعدة معرفة قابلة للمراجعة قبل التشغيل.</p>'+btn('إدارة معلومات النشاط','business')+'</div><div class="knowledge-preview"><div class="knowledge-score"><span>اكتمال المعرفة</span><b>'+([db.business.services,db.business.hours,db.business.faq].filter(Boolean).length*33)+'%</b></div><div class="progress"><i style="width:'+([db.business.services,db.business.hours,db.business.faq].filter(Boolean).length*33)+'%"></i></div><p><i class="'+(db.business.services?'done':'')+'"></i><span>الخدمات والأسعار</span><b>'+(db.business.services?'مضاف':'ناقص')+'</b></p><p><i class="'+(db.business.hours?'done':'')+'"></i><span>ساعات العمل</span><b>'+(db.business.hours?'مضاف':'ناقص')+'</b></p><p><i class="'+(db.business.faq?'done':'')+'"></i><span>الأسئلة الشائعة</span><b>'+(db.business.faq?'مضاف':'ناقص')+'</b></p><aside>إذا لم يجد المساعد معلومة مؤكدة، يطلب توضيحًا أو يحوّل المحادثة للموظف.</aside></div></section>';
if(page==='settings')screen.innerHTML=heading('الإعدادات','معلومات النشاط والاتصال')+'<div class="settings-grid"><section class="card settings-primary"><span class="card-kicker">مساحة العمل</span><h2>'+esc(db.business.name)+'</h2><p>حدّث هوية نشاطك ومعلوماته التي ستُستخدم داخل المنصة.</p>'+btn('تعديل معلومات النشاط','business')+'</section><section class="card integration-card"><div class="integration-icon">◌</div><div><span>WhatsApp Cloud API</span><h3>غير مرتبط</h3><p>لا يوجد رقم متصل أو إرسال فعلي حاليًا.</p></div><b>قريبًا</b></section><section class="card locked-setting"><span>♙</span><div><h3>الفريق والصلاحيات</h3><p>دعوة الموظفين وتحديد الوصول.</p></div><b>قريبًا</b></section><section class="card locked-setting"><span>▣</span><div><h3>الاشتراك والفواتير</h3><p>إدارة الباقة ووسائل الدفع.</p></div><b>قريبًا</b></section></div><div class="privacy-note">بيانات هذه التجربة محفوظة في هذا المتصفح فقط. لا تستخدم بيانات عملاء حساسة.</div>';
if(page==='help')screen.innerHTML=heading('المساعدة','دليل النسخة التجريبية')+'<section class="card"><h3>كيف أبدأ؟</h3><p>أضف عميلًا، افتح محادثته، أو جهّز مسودة حملة من تبويبات واتساب بزنس.</p><h3>هل تُرسل الرسائل؟</h3><p>لا. الردود والمسودات محفوظة محليًا فقط. لا يوجد اتصال بواتساب أو الذكاء الاصطناعي بعد.</p><h3>كيف أرجع؟</h3><p>استخدم التبويبات أو زر الرجوع في المتصفح. لكل قسم رابط مستقل يمكنك نسخه.</p><h3>الدعم المباشر</h3><p>قناة التواصل مع الدعم قيد التجهيز.</p></section>';
screen.querySelector('.messages')?.scrollTo(0,999999);
}
function list(q){const customers=db.customers.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q.trim().toLowerCase()));document.getElementById('list').innerHTML=customers.map(c=>route().page==='inbox'?'<a class="conversation '+(route().id===c.id?'selected':'')+'" href="#/inbox/'+c.id+'"><span class="avatar">'+esc(c.name[0])+'</span><p><strong>'+esc(c.name)+'</strong><small>'+esc(c.phone)+'</small></p></a>':'<div class="data-row"><strong>'+esc(c.name)+'</strong><span dir="ltr">'+esc(c.phone)+'</span><span>'+esc(c.tag||'جديد')+'</span><span>'+(c.consent?'مشترك':'غير مشترك')+'</span><button class="outline" data-customer="'+c.id+'">تعديل</button><a href="#/inbox/'+c.id+'">المحادثة</a></div>').join('')||'<p class="empty-note">ما لقينا نتائج مطابقة. جرّب اسمًا آخر أو رقم الجوال.</p>'}
function dialog(title,body,submit){document.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.innerHTML='<form class="editor"><div class="dialog-head"><h2>'+title+'</h2><button type="button" data-close aria-label="إغلاق">×</button></div>'+body+'<div class="actions"><button class="primary">حفظ</button><button class="outline" type="button" data-close>إلغاء</button></div></form>';document.body.append(el);el.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>el.close());el.querySelector('form').onsubmit=e=>{e.preventDefault();submit(new FormData(e.target),el)};el.showModal()}
function field(label,name,value='',type='text'){return '<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" required maxlength="200"></label>'}
function customer(id){const c=db.customers.find(x=>x.id===id)||{};dialog('بيانات العميل',field('اسم العميل','name',c.name)+field('رقم الجوال','phone',c.phone,'tel')+field('التصنيف','tag',c.tag||'جديد')+'<label><input type="checkbox" name="consent" '+(c.consent?'checked':'')+'> وافق العميل على استقبال الحملات</label>'+field('مصدر الموافقة (لا يوجد عند عدم الموافقة)','source',c.source||'لا يوجد'),(f,el)=>{const phone=f.get('phone').trim(),norm=v=>v.replace(/[^0-9]/g,'');if(norm(phone).length<7||norm(phone).length>15){notify('أدخل رقم جوال صالحًا.');return}if(db.customers.some(x=>x.id!==id&&norm(x.phone)===norm(phone))){notify('رقم الجوال موجود بالفعل.');return}if(f.has('consent')&&f.get('source').trim()==='لا يوجد'){notify('حدد مصدر الموافقة قبل الاشتراك.');return}const next=structuredClone(db),entry={...Object.fromEntries(f),id:id||crypto.randomUUID(),phone,consent:f.has('consent'),consentAt:f.has('consent')?(c.consentAt||new Date().toISOString()):null},i=next.customers.findIndex(x=>x.id===id);if(i<0)next.customers.push(entry);else next.customers[i]=entry;if(save(next)){el.close();render();notify('تم حفظ التغييرات.')}})}
function business(){dialog('معلومات النشاط',field('اسم النشاط','name',db.business.name)+['services','hours','faq'].map((k,i)=>'<label>'+['الخدمات والأسعار','ساعات العمل','الأسئلة الشائعة'][i]+'<textarea name="'+k+'">'+esc(db.business[k])+'</textarea></label>').join(''),(f,el)=>{const next=structuredClone(db);next.business=Object.fromEntries(f);if(save(next)){el.close();render();notify('تم حفظ التغييرات.')}})}
function campaign(id){const c=db.campaigns.find(x=>x.id===id)||{};dialog('تجهيز مسودة حملة','<p>الاسم ← الجمهور ← الرسالة ← المعاينة ← التوقيت ← المراجعة</p>'+field('اسم الحملة','name',c.name)+'<label>الجمهور<select name="segment"><option value="all">كل المشتركين</option><option value="جديد">عملاء جدد مشتركون</option><option value="متكرر">عملاء متكررون مشتركون</option></select></label><p id="count"></p><label>الرسالة — استخدم {{name}} للاسم<textarea name="message" required maxlength="4000">'+esc(c.message)+'</textarea></label><label>التوقيت المطلوب — الرياض UTC+3 (للتخطيط فقط)<input name="timing" type="datetime-local" value="'+esc(c.timing)+'"></label><button type="button" class="outline" id="preview">معاينة ومراجعة</button><div id="preview-text" class="preview-box" aria-live="polite"></div><p>الإرسال التجريبي والتكلفة والجدولة الفعلية غير متاحة قبل الربط.</p>',(f,el)=>{const next=structuredClone(db),entry={...Object.fromEntries(f),id:id||crypto.randomUUID()},i=next.campaigns.findIndex(x=>x.id===id);if(i<0)next.campaigns.push(entry);else next.campaigns[i]=entry;if(save(next)){el.close();render();notify('تم حفظ المسودة. لم يتم إرسال أي رسالة.')}});const form=document.querySelector('dialog form');form.segment.value=c.segment||'all';function audience(){const a=db.customers.filter(x=>x.consent&&(form.segment.value==='all'||(x.tag||'جديد')===form.segment.value));document.getElementById('count').textContent=a.length+' مستلم مؤهل. '+db.customers.filter(x=>!x.consent).length+' مستبعد لعدم الاشتراك؛ بقية الاستبعاد حسب التصنيف.';return a}form.segment.onchange=audience;audience();document.getElementById('preview').onclick=()=>document.getElementById('preview-text').textContent=(form.message.value||'لم تكتب رسالة بعد.').replaceAll('{{name}}',audience()[0]?.name||'اسم العميل')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.customer)return customer(b.dataset.customer);if(b.dataset.campaign)return campaign(b.dataset.campaign);if(b.classList.contains('mobile-menu')){const open=document.querySelector('.sidebar').classList.toggle('mobile-open');b.setAttribute('aria-expanded',String(open));return}switch(b.dataset.action){case 'customer':customer();break;case 'business':business();break;case 'campaign':campaign();break;case 'start':location.hash='/customers';notify('اختر المحادثة بجانب العميل، أو أضف عميلًا جديدًا.')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.sidebar').classList.remove('mobile-open');document.querySelector('.mobile-menu').setAttribute('aria-expanded','false')}});
function connectivity(){document.getElementById('connection').textContent=navigator.onLine?'':'أنت غير متصل. يمكنك متابعة التجربة والحفظ محليًا.'}
window.addEventListener('hashchange',render);window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);connectivity();render();
