const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db;const seed={customers:[{id:'sara',name:'سارة',phone:'0500000001',consent:false},{id:'reem',name:'ريم',phone:'0500000002',consent:true},{id:'lina',name:'لينا',phone:'0500000003',consent:false}],messages:{sara:['مرحبًا، أحتاج معلومات عن الخدمات.'],reem:['شكرًا على المتابعة.'],lina:['ما هي ساعات العمل؟']},campaigns:[],business:{name:'نشاطك',services:'',hours:'',faq:''}};
try{db=JSON.parse(localStorage.getItem('tugx-v3'))||structuredClone(seed)}catch{db=structuredClone(seed)}
function notify(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4500)}
function save(next){try{localStorage.setItem('tugx-v3',JSON.stringify(next));db=next;return true}catch{notify('تعذر حفظ التغييرات. حاول مرة أخرى؛ ما كتبته ما زال موجودًا.');return false}}
const names={dashboard:'نظرة عامة',inbox:'المحادثات',campaigns:'الحملات',customers:'العملاء',templates:'القوالب',automation:'الأتمتة',ai:'مساعد توجيكس AI',settings:'الإعدادات',help:'المساعدة'},wa=['inbox','campaigns','customers','templates','automation'];
const main=document.querySelector('main');
main.innerHTML='<header><button class="mobile-menu" aria-label="فتح القائمة" aria-expanded="false">☰</button><div class="crumb"></div><a href="#/help">المساعدة</a></header><div class="demo-banner">نسخة تجريبية — البيانات المعروضة توضيحية. الحفظ على هذا المتصفح فقط، ولا يتم إرسال رسائل فعلية.</div><div id="connection" role="status"></div><section id="screen" class="view active"></section>';
document.querySelector('.sidebar nav').innerHTML=['dashboard','inbox','ai'].map(k=>'<a class="nav" href="#/'+k+'" data-nav="'+k+'">'+(k==='inbox'?'واتساب بزنس':names[k])+'</a>').join('');
document.querySelector('.sidebar-bottom').innerHTML='<a class="nav" href="#/settings">الإعدادات</a><a class="nav" href="#/help">المساعدة</a><div class="user">مساحة العمل التجريبية</div>';
const screen=document.getElementById('screen');
function route(){const p=location.hash.slice(1).split('/').filter(Boolean);return{page:names[p[0]]?p[0]:'dashboard',id:p[1]||''}}
function tabs(page){return '<nav class="wa-tabs" aria-label="أقسام واتساب">'+wa.map(k=>'<a href="#/'+k+'" class="'+(k===page?'selected':'')+'" '+(k===page?'aria-current="page"':'')+'>'+names[k]+(['templates','automation'].includes(k)?'<small>قريبًا</small>':'')+'</a>').join('')+'</nav>'}
function heading(t,d,a=''){return '<div class="page-title"><div><h1>'+t+'</h1><p>'+d+'</p></div>'+a+'</div>'}
function btn(t,a){return '<button class="primary" data-action="'+a+'">'+t+'</button>'}
function render(){
const {page,id}=route();document.title=names[page]+' | توجيكس';document.querySelector('.crumb').innerHTML=esc(db.business.name)+' / '+(wa.includes(page)?'<a href="#/inbox">واتساب بزنس</a> ← ':'')+names[page];
document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(wa.includes(page)?'inbox':page)));document.querySelector('.sidebar').classList.remove('mobile-open');document.querySelector('.mobile-menu').setAttribute('aria-expanded','false');
if(page==='dashboard')screen.innerHTML=heading('كل شيء في مكانه','تابع المحادثات التي تحتاج ردًا، ونتائج حملاتك، وأداء مساعدك.')+'<div class="stats"><article><p>العملاء في التجربة</p><h2>'+db.customers.length+'</h2><a href="#/customers">عرض العملاء</a></article><article><p>مسودات الحملات</p><h2>'+db.campaigns.length+'</h2><a href="#/campaigns">عرض الحملات</a></article><article><p>اتصال واتساب</p><h2>غير مرتبط</h2><a href="#/settings">تفاصيل الاتصال</a></article><article><p>المساعد الذكي</p><h2>غير مفعّل</h2><a href="#/ai">إعداد المعلومات</a></article></div><section class="card"><h3>ابدأ بخطوات واضحة</h3><p>ربط واتساب قيد التطوير. يمكنك الآن تنظيم العملاء وتجهيز المسودات.</p><div class="actions"><a href="#/customers">١. أضف عميلًا</a><a href="#/ai">٢. أضف معلومات النشاط</a><a href="#/campaigns">٣. جهّز مسودة حملة</a></div></section>';
if(page==='inbox'){
const c=db.customers.find(x=>x.id===id);
screen.innerHTML=heading('واتساب بزنس','نظّم محادثات العملاء، وتابع الطلبات، ووزّع العمل على فريقك.',btn('بدء محادثة','start'))+tabs(page)+'<div class="inbox '+(c?'chat-open':'')+'"><aside class="conversations"><input id="search" aria-label="بحث المحادثات" placeholder="ابحث باسم العميل أو رقم الجوال"><div id="list"></div></aside><section class="chat">'+(c?'<div class="chat-head"><a class="outline" href="#/inbox">المحادثات</a><strong>'+esc(c.name)+'</strong><span>محادثة توضيحية</span></div><div class="messages">'+(db.messages[id]||[]).map(m=>'<div class="message '+(typeof m==='object'?'outbound':'inbound')+'">'+esc(typeof m==='object'?m.text:m)+'<small>'+(typeof m==='object'?'محفوظ محليًا — لم يُرسل':'رسالة توضيحية')+'</small></div>').join('')+'</div><form id="reply" class="composer"><input name="text" aria-label="الرسالة" required maxlength="4000" placeholder="اكتب ردًا تجريبيًا…"><button class="send">حفظ الرد التجريبي</button></form>':'<div class="empty"><h2>اختر محادثة</h2><p>تظهر هنا رسائل العميل المحدد.</p></div>')+'</section></div>';
list('');document.getElementById('search').oninput=e=>list(e.target.value);document.getElementById('reply')?.addEventListener('submit',e=>{e.preventDefault();const text=e.target.text.value.trim();if(!text)return;const next=structuredClone(db);(next.messages[id]??=[]).push({text});if(save(next)){render();notify('حُفظ الرد في التجربة فقط. لم يُرسل إلى واتساب.')}});
}
if(page==='customers'){screen.innerHTML=heading('العملاء','احتفظ ببيانات عملائك وسجل تواصلهم وتصنيفاتهم في مكان واحد.',btn('إضافة عميل','customer'))+tabs(page)+'<input class="search-field" id="search" aria-label="بحث العملاء" placeholder="ابحث باسم العميل أو رقم الجوال"><section class="card" id="list"></section>';list('');document.getElementById('search').oninput=e=>list(e.target.value)}
if(page==='campaigns')screen.innerHTML=heading('الحملات','أنشئ حملات لعملائك المشتركين، وحدد جمهورك، وتابع النتائج.',btn('إنشاء مسودة حملة','campaign'))+tabs(page)+'<section class="card"><p>حفظ المسودات متاح محليًا. الإرسال والجدولة الفعلية قيد التطوير.</p>'+(db.campaigns.map(c=>'<div class="data-row"><strong>'+esc(c.name)+'</strong><span>مسودة</span><button class="outline" data-campaign="'+c.id+'">عرض وتعديل</button></div>').join('')||'<div class="empty"><h2>حملتك الأولى تبدأ هنا</h2><p>اختر جمهورك وجهّز رسالتك، ثم راجعها قبل حفظ المسودة.</p></div>')+'</section>';
if(['templates','automation'].includes(page))screen.innerHTML=heading(names[page],'واتساب بزنس')+tabs(page)+'<section class="card empty"><span>قريبًا</span><h2>هذه الميزة قيد التطوير، وستتوفر لاحقًا.</h2><a href="#/inbox">العودة إلى محادثات واتساب</a></section>';
if(page==='ai')screen.innerHTML=heading(names.ai,'زوّد مساعدك بمعلومات نشاطك، واختبر إجاباته قبل تفعيل الرد التلقائي.')+'<section class="card"><span class="status draft">غير مفعّل — الربط بالذكاء الاصطناعي قريبًا</span><h2>معرفة منظّمة، وإجابات أوضح</h2><p>احفظ الخدمات والأسعار وساعات العمل والأسئلة الشائعة. اختبار الردود والتشغيل التلقائي قيد التطوير.</p>'+btn('إدارة معلومات النشاط','business')+'<p>عند تنفيذ المساعد: إذا لم يجد معلومة مؤكدة، يطلب توضيحًا أو يحوّل للموظف.</p></section>';
if(page==='settings')screen.innerHTML=heading('الإعدادات','معلومات النشاط والاتصال')+'<section class="card"><h3>'+esc(db.business.name)+'</h3>'+btn('تعديل معلومات النشاط','business')+'<hr><h3>واتساب غير مرتبط</h3><p>الربط الرسمي قيد التطوير. لا يوجد رقم متصل أو إرسال فعلي.</p><p>الفريق والصلاحيات والاشتراكات: قريبًا.</p><p>بيانات التجربة محفوظة في هذا المتصفح فقط. لا تستخدم بيانات عملاء حساسة.</p></section>';
if(page==='help')screen.innerHTML=heading('المساعدة','دليل النسخة التجريبية')+'<section class="card"><h3>كيف أبدأ؟</h3><p>أضف عميلًا، افتح محادثته، أو جهّز مسودة حملة من تبويبات واتساب بزنس.</p><h3>هل تُرسل الرسائل؟</h3><p>لا. الردود والمسودات محفوظة محليًا فقط. لا يوجد اتصال بواتساب أو الذكاء الاصطناعي بعد.</p><h3>كيف أرجع؟</h3><p>استخدم التبويبات أو زر الرجوع في المتصفح. لكل قسم رابط مستقل يمكنك نسخه.</p><h3>الدعم المباشر</h3><p>قناة التواصل مع الدعم قيد التجهيز.</p></section>';
screen.querySelector('.messages')?.scrollTo(0,999999);
}
function list(q){const customers=db.customers.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q.trim().toLowerCase()));document.getElementById('list').innerHTML=customers.map(c=>route().page==='inbox'?'<a class="conversation '+(route().id===c.id?'selected':'')+'" href="#/inbox/'+c.id+'"><span class="avatar">'+esc(c.name[0])+'</span><p><strong>'+esc(c.name)+'</strong><small>'+esc(c.phone)+'</small></p></a>':'<div class="data-row"><strong>'+esc(c.name)+'</strong><span dir="ltr">'+esc(c.phone)+'</span><span>'+esc(c.tag||'جديد')+'</span><span>'+(c.consent?'مشترك':'غير مشترك')+'</span><button class="outline" data-customer="'+c.id+'">تعديل</button><a href="#/inbox/'+c.id+'">المحادثة</a></div>').join('')||'<p class="empty-note">ما لقينا نتائج مطابقة. جرّب اسمًا آخر أو رقم الجوال.</p>'}
function dialog(title,body,submit){document.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.innerHTML='<form class="editor"><div class="dialog-head"><h2>'+title+'</h2><button type="button" data-close aria-label="إغلاق">×</button></div>'+body+'<div class="actions"><button class="primary">حفظ</button><button class="outline" type="button" data-close>إلغاء</button></div></form>';document.body.append(el);el.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>el.close());el.querySelector('form').onsubmit=e=>{e.preventDefault();submit(new FormData(e.target),el)};el.showModal()}
function field(label,name,value='',type='text'){return '<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" required maxlength="200"></label>'}
function customer(id){const c=db.customers.find(x=>x.id===id)||{};dialog('بيانات العميل',field('اسم العميل','name',c.name)+field('رقم الجوال','phone',c.phone,'tel')+field('التصنيف','tag',c.tag||'جديد')+'<label><input type="checkbox" name="consent" '+(c.consent?'checked':'')+'> وافق العميل على استقبال الحملات</label>'+field('مصدر الموافقة (لا يوجد عند عدم الموافقة)','source',c.source||'لا يوجد'),(f,el)=>{const phone=f.get('phone').trim(),norm=v=>v.replace(/[^0-9]/g,'');if(norm(phone).length<7||norm(phone).length>15){notify('أدخل رقم جوال صالحًا.');return}if(db.customers.some(x=>x.id!==id&&norm(x.phone)===norm(phone))){notify('رقم الجوال موجود بالفعل.');return}if(f.has('consent')&&f.get('source').trim()==='لا يوجد'){notify('حدد مصدر الموافقة قبل الاشتراك.');return}const next=structuredClone(db),entry={...Object.fromEntries(f),id:id||crypto.randomUUID(),phone,consent:f.has('consent'),consentAt:f.has('consent')?(c.consentAt||new Date().toISOString()):null},i=next.customers.findIndex(x=>x.id===id);if(i<0)next.customers.push(entry);else next.customers[i]=entry;if(save(next)){el.close();render();notify('تم حفظ التغييرات.')}})}
function business(){dialog('معلومات النشاط',field('اسم النشاط','name',db.business.name)+['services','hours','faq'].map((k,i)=>'<label>'+['الخدمات والأسعار','ساعات العمل','الأسئلة الشائعة'][i]+'<textarea name="'+k+'">'+esc(db.business[k])+'</textarea></label>').join(''),(f,el)=>{const next=structuredClone(db);next.business=Object.fromEntries(f);if(save(next)){el.close();render();notify('تم حفظ التغييرات.')}})}
function campaign(id){const c=db.campaigns.find(x=>x.id===id)||{};dialog('تجهيز مسودة حملة','<p>الاسم ← الجمهور ← الرسالة ← المعاينة ← التوقيت ← المراجعة</p>'+field('اسم الحملة','name',c.name)+'<label>الجمهور<select name="segment"><option value="all">كل المشتركين</option><option value="جديد">عملاء جدد مشتركون</option><option value="متكرر">عملاء متكررون مشتركون</option></select></label><p id="count"></p><label>الرسالة — استخدم {{name}} للاسم<textarea name="message" required maxlength="4000">'+esc(c.message)+'</textarea></label><label>التوقيت المطلوب — الرياض UTC+3 (للتخطيط فقط)<input name="timing" type="datetime-local" value="'+esc(c.timing)+'"></label><button type="button" class="outline" id="preview">معاينة ومراجعة</button><div id="preview-text" class="preview-box" aria-live="polite"></div><p>الإرسال التجريبي والتكلفة والجدولة الفعلية غير متاحة قبل الربط.</p>',(f,el)=>{const next=structuredClone(db),entry={...Object.fromEntries(f),id:id||crypto.randomUUID()},i=next.campaigns.findIndex(x=>x.id===id);if(i<0)next.campaigns.push(entry);else next.campaigns[i]=entry;if(save(next)){el.close();render();notify('تم حفظ المسودة. لم يتم إرسال أي رسالة.')}});const form=document.querySelector('dialog form');form.segment.value=c.segment||'all';function audience(){const a=db.customers.filter(x=>x.consent&&(form.segment.value==='all'||(x.tag||'جديد')===form.segment.value));document.getElementById('count').textContent=a.length+' مستلم مؤهل. '+db.customers.filter(x=>!x.consent).length+' مستبعد لعدم الاشتراك؛ بقية الاستبعاد حسب التصنيف.';return a}form.segment.onchange=audience;audience();document.getElementById('preview').onclick=()=>document.getElementById('preview-text').textContent=(form.message.value||'لم تكتب رسالة بعد.').replaceAll('{{name}}',audience()[0]?.name||'اسم العميل')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.customer)return customer(b.dataset.customer);if(b.dataset.campaign)return campaign(b.dataset.campaign);if(b.classList.contains('mobile-menu')){const open=document.querySelector('.sidebar').classList.toggle('mobile-open');b.setAttribute('aria-expanded',String(open));return}switch(b.dataset.action){case 'customer':customer();break;case 'business':business();break;case 'campaign':campaign();break;case 'start':location.hash='/customers';notify('اختر المحادثة بجانب العميل، أو أضف عميلًا جديدًا.')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.sidebar').classList.remove('mobile-open');document.querySelector('.mobile-menu').setAttribute('aria-expanded','false')}});
function connectivity(){document.getElementById('connection').textContent=navigator.onLine?'':'أنت غير متصل. يمكنك متابعة التجربة والحفظ محليًا.'}
window.addEventListener('hashchange',render);window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);connectivity();render();
